Repository testing-library/eslint-plugin-testing-library, pull requests merged in 2020-06, with the labels that each got.

#161 fix: ensure node exists before using in isArrowFunctionExpression
  lib/node-utils.ts
  tests/lib/rules/prefer-find-by.test.ts
Labels: bug

#164 ci: include eslint matrix
  .travis.yml
  package.json
Labels: chore

#169 feat: recommend prefer-screen-queries
  README.md
  lib/index.ts
  lib/rules/prefer-screen-queries.ts
  tests/__snapshots__/index.test.ts.snap
Labels: enhancement

#168 feat: recommend no-wait-for-empty-callback
  README.md
  lib/index.ts
  lib/rules/no-wait-for-empty-callback.ts
  tests/__snapshots__/index.test.ts.snap
Labels: enhancement

#179 test: include tests from methods not available in screen
  docs/rules/prefer-screen-queries.md
  tests/lib/rules/prefer-screen-queries.test.ts
Labels: documentation

#177 feat: add no-container rule
  README.md
  docs/rules/no-container.md
  lib/index.ts
  lib/node-utils.ts
  lib/rules/no-container.ts
  lib/rules/no-debug.ts
  tests/__snapshots__/index.test.ts.snap
  tests/lib/rules/no-container.test.ts
Labels: new rule

#184 refactor: rename recommended config to dom
  README.md
  lib/index.ts
  tests/__snapshots__/index.test.ts.snap
  tests/index.test.ts
Labels: BREAKING CHANGE, documentation, enhancement
