Repository testing-library/eslint-plugin-testing-library, pull requests merged in 2021-09, with the labels that each got.

#461 chore: update dependencies
  package.json
Labels: dependencies, chore

#463 chore: bump supported node version
  .github/workflows/pipeline.yml
  package.json
Labels: BREAKING CHANGE, chore

#464 chore: update dependencies
  package.json
Labels: dependencies, chore

#469 feat(no-debug): rename to `no-debugging-utils`
  CONTRIBUTING.md
  README.md
  docs/rules/no-debugging-utils.md
  lib/configs/angular.ts
  lib/configs/react.ts
  lib/configs/vue.ts
  lib/rules/no-debugging-utils.ts
  tests/__snapshots__/index.test.ts.snap
  tests/lib/rules/no-debugging-utils.test.ts
Labels: BREAKING CHANGE

#468 feat(no-unnecessary-act): add to React config by default
  README.md
  lib/configs/react.ts
  lib/rules/no-unnecessary-act.ts
  tests/__snapshots__/index.test.ts.snap
Labels: enhancement, BREAKING CHANGE

#470 docs: cleanup migration guide docs
  README.md
  docs/migration-guides/v4.md
Labels: documentation

#473 ci: fix node 16 to 16.8
  .github/workflows/pipeline.yml
Labels: chore

#472 fix(prefer-find-by): stop prefer-find-by fixer to break code when no …
  lib/rules/prefer-find-by.ts
  tests/lib/rules/prefer-find-by.test.ts
Labels: bug

#482 revert: "ci: fix node 16 to 16.8"
  .github/workflows/pipeline.yml
Labels: chore
