Repository testing-library/eslint-plugin-testing-library, pull requests merged in 2021-04, with the labels that each got.

#349 fix: allow console.debug() in no-debug
  lib/detect-testing-library-utils.ts
  lib/rules/no-debug.ts
  tests/lib/rules/no-debug.test.ts
Labels: bug

#353 docs: add new badges to README
  README.md
Labels: documentation

#361 chore: prettify codebase
  .github/workflows/pipeline.yml
  .lintstagedrc
  package.json
Labels: chore
