Repository testing-library/eslint-plugin-testing-library, pull requests merged in 2021-05, with the labels that each got.

#363 feat(no-wait-for-side-effects): report render in waitFor
  docs/rules/no-wait-for-side-effects.md
  lib/node-utils/is-node-of-type.ts
  lib/rules/no-wait-for-side-effects.ts
  tests/lib/rules/no-wait-for-side-effects.test.ts
Labels: enhancement

#369 docs: update `no-wait-for-empty-callback` docs
  docs/rules/no-wait-for-empty-callback.md
Labels: documentation

#374 fix(await-async-query): get correct Identifier related to CallExpression
  lib/rules/await-async-query.ts
  tests/lib/rules/await-async-query.test.ts
Labels: bug

#365 feat: new `no-unnecessary-act` rule
  README.md
  docs/rules/no-unnecessary-act.md
  lib/create-testing-library-rule/detect-testing-library-utils.ts
  lib/node-utils/index.ts
  lib/rules/no-unnecessary-act.ts
  lib/rules/no-wait-for-empty-callback.ts
  tests/index.test.ts
  tests/lib/rules/no-unnecessary-act.test.ts
Labels: new rule

#357 feat(no-debug): support `utilNames` option
  README.md
  docs/rules/no-debug.md
  lib/create-testing-library-rule/detect-testing-library-utils.ts
  lib/rules/no-debug.ts
  lib/utils/index.ts
  tests/lib/rules/no-debug.test.ts
Labels: enhancement

#350 chore: add tests for Node 16
  .github/workflows/pipeline.yml
Labels: chore, dependencies

#390 fix: update dependencies
  jest.config.js
  lib/configs/index.ts
  package.json
  tests/lib/rules/consistent-data-testid.test.ts
  tools/generate-configs/index.ts
  tools/generate-configs/utils.ts
Labels: chore, dependencies

#388 feat(prefer-screen-queries): detect render in wrappers correctly
  lib/rules/prefer-screen-queries.ts
  tests/lib/rules/prefer-screen-queries.test.ts
Labels: enhancement

#387 docs: add semantic versioning policy
  README.md
  docs/semantic-versioning-policy.md
Labels: documentation
