Repository testing-library/eslint-plugin-testing-library, pull requests merged in 2021-07, with the labels that each got.

#398 feat: add support for fireEvent as function in prefer-user-event
  docs/rules/prefer-user-event.md
  lib/create-testing-library-rule/detect-testing-library-utils.ts
  lib/rules/prefer-user-event.ts
  tests/lib/rules/prefer-user-event.test.ts
Labels: enhancement

#397 refactor: automatically generate the rules-list in README
  README.md
  lib/rules/await-async-utils.ts
  lib/rules/await-fire-event.ts
  lib/rules/no-container.ts
  lib/rules/no-wait-for-empty-callback.ts
  lib/rules/no-wait-for-multiple-assertions.ts
  lib/rules/no-wait-for-side-effects.ts
  lib/rules/prefer-find-by.ts
  lib/rules/prefer-presence-queries.ts
  lib/rules/prefer-screen-queries.ts
  lib/rules/prefer-user-event.ts
  lib/utils/types.ts
  package.json
  tools/generate-rules-list/index.ts
  tools/generate-rules-list/utils.ts
Labels: documentation

#408 chore: prevent stalebot to close issues flagged as bug
  .github/stale.yml
Labels: chore

#410 fix(prefer-query-by-disappearance): fix rule name
  lib/rules/prefer-query-by-disappearance.ts
Labels: bug

#422 fix(prefer-user-event): prevent crash with custom `createEvent` function
  lib/rules/prefer-user-event.ts
  tests/lib/rules/prefer-user-event.test.ts
Labels: bug
