Repository testing-library/eslint-plugin-testing-library, pull requests merged in 2022-10, with the labels that each got.

#657 fix(no-dom-imports): false negatives with several testing library imports
  docs/rules/no-dom-import.md
  lib/create-testing-library-rule/detect-testing-library-utils.ts
  lib/rules/no-dom-import.ts
  tests/lib/rules/no-dom-import.test.ts
Labels: hacktoberfest-accepted

#658 fix(no-node-access): false positives with `props.children`
  docs/rules/no-node-access.md
  lib/rules/no-node-access.ts
  tests/lib/rules/no-node-access.test.ts
Labels: hacktoberfest-accepted

#666 feat(no-await-sync-query): rename to `no-await-sync-queries`
  README.md
  docs/rules/no-await-sync-queries.md
  lib/configs/angular.ts
  lib/configs/dom.ts
  lib/configs/marko.ts
  lib/configs/react.ts
  lib/configs/vue.ts
  lib/rules/no-await-sync-queries.ts
  tests/__snapshots__/index.test.ts.snap
  tests/lib/rules/no-await-sync-queries.test.ts
Labels: BREAKING CHANGE, v6

#667 feat(no-await-sync-events): add to DOM, Angular & React configs by default
  README.md
  lib/configs/angular.ts
  lib/configs/dom.ts
  lib/configs/react.ts
  lib/rules/no-await-sync-events.ts
  tests/__snapshots__/index.test.ts.snap
Labels: BREAKING CHANGE, v6

#665 feat(await-async-query): rename to `await-async-queries`
  README.md
  docs/rules/await-async-queries.md
  lib/configs/angular.ts
  lib/configs/dom.ts
  lib/configs/marko.ts
  lib/configs/react.ts
  lib/configs/vue.ts
  lib/rules/await-async-queries.ts
  tests/__snapshots__/index.test.ts.snap
  tests/lib/rules/await-async-queries.test.ts
Labels: BREAKING CHANGE, v6

#670 fix(await-async-event): pluralize to await-async-events
  README.md
  docs/rules/await-async-events.md
  docs/rules/no-await-sync-events.md
  lib/configs/angular.ts
  lib/configs/dom.ts
  lib/configs/marko.ts
  lib/configs/react.ts
  lib/configs/vue.ts
  lib/rules/await-async-events.ts
  tests/__snapshots__/index.test.ts.snap
  tests/lib/rules/await-async-events.test.ts
Labels: v6

#675 fix(await-async-events): improve fixer
  lib/node-utils/index.ts
  lib/node-utils/is-node-of-type.ts
  lib/rules/await-async-events.ts
  tests/lib/rules/await-async-events.test.ts
Labels: enhancement, v6

#677 fix(no-wait-for-side-effects): false negatives in variables declarations
  lib/rules/no-wait-for-side-effects.ts
  tests/lib/rules/no-wait-for-side-effects.test.ts
Labels: hacktoberfest-accepted

#678 feat(no-global-regexp-flag-in-query): Detect global RegExp in variable declarations
  lib/rules/no-global-regexp-flag-in-query.ts
  tests/lib/rules/no-global-regexp-flag-in-query.test.ts
Labels: hacktoberfest-accepted

#612 feat(await-async-query,await-async-utils,await-fire-event): support handling promises with `jest-extended`'s `.toResolve` & `.toRejects`
  docs/rules/await-async-query.md
  docs/rules/await-async-utils.md
  docs/rules/await-fire-event.md
  lib/node-utils/index.ts
  tests/lib/rules/await-async-query.test.ts
  tests/lib/rules/await-async-utils.test.ts
  tests/lib/rules/await-fire-event.test.ts
Labels: enhancement

#682 chore: add init gitpod config
  .gitpod.yml
Labels: chore
