Repository testing-library/eslint-plugin-testing-library, pull requests merged in 2024-10, with the labels that each got.

#935 chore: add editorconfig file
  .editorconfig
Labels: chore

#938 chore: remove `bahmutov/npm-install` usage
  .github/workflows/release.yml
  .github/workflows/verifications.yml
Labels: chore, github_actions

#942 ci: use Node 20 for main tests
  .nvmrc
Labels: chore

#934 fix(no-manual-cleanup): properly check all `@testing-library` imports
  lib/rules/no-manual-cleanup.ts
  tests/lib/rules/no-manual-cleanup.test.ts
Labels: bug

#939 fix: generate provenance statements on release
  .github/workflows/release.yml
Labels: github_actions

#941 ci: add tests for Node 20 & 22
  .github/workflows/verifications.yml
Labels: chore

#932 chore(deps-dev): upgrade Prettier to v3
  .prettierignore
  .prettierrc.js
  lib/create-testing-library-rule/detect-testing-library-utils.ts
  lib/create-testing-library-rule/index.ts
  lib/rules/await-async-events.ts
  lib/rules/consistent-data-testid.ts
  lib/rules/no-render-in-lifecycle.ts
  lib/rules/prefer-explicit-assert.ts
  lib/rules/prefer-presence-queries.ts
  lib/rules/prefer-query-matchers.ts
  lib/utils/types.ts
  package-lock.json
  package.json
  tests/create-testing-library-rule.test.ts
  tests/lib/rules/await-async-events.test.ts
  tests/lib/rules/await-async-queries.test.ts
  tests/lib/rules/await-async-utils.test.ts
  tests/lib/rules/no-await-sync-events.test.ts
  tests/lib/rules/no-await-sync-queries.test.ts
  tests/lib/rules/no-container.test.ts
  tests/lib/rules/no-debugging-utils.test.ts
  tests/lib/rules/no-dom-import.test.ts
  tests/lib/rules/no-manual-cleanup.test.ts
  tests/lib/rules/no-render-in-lifecycle.test.ts
  tests/lib/rules/no-unnecessary-act.test.ts
  tests/lib/rules/no-wait-for-multiple-assertions.test.ts
  tests/lib/rules/no-wait-for-side-effects.test.ts
  tests/lib/rules/no-wait-for-snapshot.test.ts
  tests/lib/rules/prefer-explicit-assert.test.ts
  tests/lib/rules/prefer-find-by.test.ts
  tests/lib/rules/prefer-implicit-assert.test.ts
  tests/lib/rules/prefer-screen-queries.test.ts
  tests/lib/rules/prefer-user-event.test.ts
  tools/generate-configs/index.ts
  tools/generate-configs/utils.ts
Labels: dependencies

#940 fix: update dependencies
  package-lock.json
  package.json
Labels: dependencies

#944 feat: drop ESLint v7 support
  .github/workflows/verifications.yml
  docs/migration-guides/v7.md
  package-lock.json
  package.json
Labels: BREAKING CHANGE, v7

#945 feat(deps): update to `@typescript-eslint/*` v6
  .eslintrc.js
  lib/configs/index.ts
  lib/create-testing-library-rule/detect-testing-library-utils.ts
  lib/create-testing-library-rule/index.ts
  lib/index.ts
  lib/node-utils/index.ts
  lib/rules/await-async-events.ts
  lib/rules/no-debugging-utils.ts
  lib/rules/no-dom-import.ts
  lib/rules/no-render-in-lifecycle.ts
  lib/rules/prefer-explicit-assert.ts
  lib/utils/compat.ts
  lib/utils/types.ts
  package-lock.json
  package.json
  tests/lib/FlatCompatRuleTester.ts
  tests/lib/test-utils.ts
Labels: v7

#947 feat(deps): update to `@typescript-eslint/*` v7
  lib/create-testing-library-rule/detect-testing-library-utils.ts
  lib/create-testing-library-rule/index.ts
  lib/rules/no-await-sync-events.ts
  lib/rules/prefer-query-by-disappearance.ts
  lib/utils/types.ts
  package-lock.json
  package.json
Labels: v7
