Repository testing-library/eslint-plugin-testing-library, pull requests merged in 2024-11, with the labels that each got.

#954 feat(deps-dev): update `eslint-plugin-jest`
  package-lock.json
  package.json
Labels: dependencies, v7

#955 feat(deps): update to `@typescript-eslint/*` v8
  lib/create-testing-library-rule/detect-testing-library-utils.ts
  lib/create-testing-library-rule/index.ts
  lib/index.ts
  lib/node-utils/index.ts
  lib/rules/index.ts
  lib/rules/no-manual-cleanup.ts
  lib/utils/file-import.ts
  lib/utils/types.ts
  lint-staged.config.js
  package-lock.json
  package.json
  tests/eslint-remote-tester.config.js
  tests/index.test.ts
  tests/lib/FlatCompatRuleTester.ts
  tests/lib/test-utils.ts
  tools/generate-configs/index.ts
  tools/generate-configs/utils.ts
Labels: v7

#960 chore: use Node 22 for main tests
  .nvmrc
Labels: chore

#901 chore: v7
  .eslintrc.js
  .github/workflows/verifications.yml
  README.md
  docs/migration-guides/v7.md
  lib/configs/index.ts
  lib/create-testing-library-rule/detect-testing-library-utils.ts
  lib/create-testing-library-rule/index.ts
  lib/index.ts
  lib/node-utils/index.ts
  lib/rules/await-async-events.ts
  lib/rules/index.ts
  lib/rules/no-await-sync-events.ts
  lib/rules/no-debugging-utils.ts
  lib/rules/no-dom-import.ts
  lib/rules/no-manual-cleanup.ts
  lib/rules/no-render-in-lifecycle.ts
  lib/rules/prefer-explicit-assert.ts
  lib/rules/prefer-query-by-disappearance.ts
  lib/utils/compat.ts
  lib/utils/file-import.ts
  lib/utils/types.ts
  lint-staged.config.js
  package-lock.json
  package.json
  tests/eslint-remote-tester.config.js
  tests/index.test.ts
  tests/lib/FlatCompatRuleTester.ts
  tests/lib/test-utils.ts
  tools/generate-configs/index.ts
  tools/generate-configs/utils.ts
Labels: BREAKING CHANGE, v7

#967 chore: update dependencies
  .husky/commit-msg
  .husky/pre-commit
  lib/node-utils/index.ts
  package.json
  pnpm-lock.yaml
Labels: dependencies
