Repository testing-library/eslint-plugin-testing-library, pull requests merged in 2025-05, with the labels that each got.

#1006 feat: add `no-test-id-queries` rule
  README.md
  docs/rules/no-test-id-queries.md
  lib/rules/no-test-id-queries.ts
  tests/index.test.ts
  tests/lib/rules/no-test-id-queries.test.ts
Labels: new rule

#1009 fix(await-async-queries): false positive with optional chaining
  lib/node-utils/index.ts
  tests/lib/rules/await-async-queries.test.ts
Labels: bug

#1012 chore: update issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/propose_new_rule.yml
  .github/ISSUE_TEMPLATE/request_general_change.yml
  .github/ISSUE_TEMPLATE/request_rule_change.yml
Labels: chore

#1013 feat(prefer-find-by): add fixer for waitFor wrapping findBy queries
  docs/rules/prefer-find-by.md
  lib/rules/prefer-find-by.ts
  tests/lib/rules/prefer-find-by.test.ts
Labels: enhancement
